"""empty message

Revision ID: 1fe2c4a10c1c
Revises: 
Create Date: 2025-02-21 18:18:31.914810

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1fe2c4a10c1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('system_config',
    sa.Column('config_id', sa.Integer(), autoincrement=True, nullable=False, comment='設定ID（ユニーク）'),
    sa.Column('key', sa.String(length=255), nullable=False, comment='設定キー'),
    sa.Column('value', sa.Text(), nullable=False, comment='設定値'),
    sa.Column('description', sa.Text(), nullable=True, comment='説明'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新日時'),
    sa.PrimaryKeyConstraint('config_id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('reports',
    sa.Column('report_id', sa.Integer(), autoincrement=True, nullable=False, comment='レポートID'),
    sa.Column('student_id', sa.String(length=5), nullable=False, comment='学生ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='内容'),
    sa.Column('image_paths', sa.String(length=255), nullable=True, comment='画像パス'),
    sa.Column('video_paths', sa.String(length=255), nullable=True, comment='動画パス'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新日時'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('student_auth',
    sa.Column('student_id', sa.String(length=5), nullable=False, comment='生徒ID（students参照）'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='パスワードハッシュ'),
    sa.Column('last_login', sa.DateTime(), nullable=True, comment='最終ログイン日時'),
    sa.Column('login_attempts', sa.Integer(), nullable=True, comment='ログイン試行回数'),
    sa.Column('is_locked', sa.Boolean(), nullable=True, comment='アカウントロックフラグ'),
    sa.Column('reset_token', sa.String(length=100), nullable=True, comment='パスワードリセットトークン'),
    sa.Column('reset_token_expires', sa.DateTime(), nullable=True, comment='トークン有効期限'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新日時'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('student_base_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_contacts',
    sa.Column('student_id', sa.String(length=5), nullable=False, comment='生徒ID（students参照）'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='電話番号'),
    sa.Column('emergency_contact', sa.String(length=255), nullable=True, comment='緊急連絡先'),
    sa.Column('emergency_phone', sa.String(length=20), nullable=True, comment='緊急連絡先電話番号'),
    sa.Column('address', sa.String(length=255), nullable=True, comment='住所'),
    sa.Column('postal_code', sa.String(length=8), nullable=True, comment='郵便番号'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新日時'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('student_profiles',
    sa.Column('student_id', sa.String(length=5), nullable=False, comment='生徒ID（students参照）'),
    sa.Column('profile_image_path', sa.String(length=255), nullable=True, comment='プロフィール画像パス'),
    sa.Column('bio', sa.Text(), nullable=True, comment='自己紹介'),
    sa.Column('interests', sa.Text(), nullable=True, comment='興味・関心'),
    sa.Column('skills', sa.Text(), nullable=True, comment='スキル'),
    sa.Column('github_url', sa.String(length=255), nullable=True, comment='GitHubのURL'),
    sa.Column('portfolio_url', sa.String(length=255), nullable=True, comment='ポートフォリオのURL'),
    sa.Column('is_public', sa.Boolean(), nullable=True, comment='公開フラグ'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新日時'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('schedule_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['student_base_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('comments')
    op.drop_table('private_chat')
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_important', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.alter_column('announcement_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='お知らせID（ユニーク）',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='タイトル',
               existing_nullable=False)
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='内容',
               existing_nullable=False)
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='作成者の教師ID（teachers参照）',
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_constraint('fk_announcement_teacher', type_='foreignkey')
        batch_op.create_foreign_key('fk_announcement_teacher', 'teachers', ['created_by'], ['teacher_id'])

    with op.batch_alter_table('bulletin_board', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bulletin_id', sa.Integer(), autoincrement=True, nullable=False, comment='掲示板ID'))
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=False, comment='タイトル'))
        batch_op.add_column(sa.Column('created_by', sa.String(length=5), nullable=False, comment='作成者（学生）ID'))
        batch_op.add_column(sa.Column('approved_by', sa.Integer(), nullable=True, comment='承認者（教員）ID'))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True, comment='承認/拒否日時'))
        batch_op.add_column(sa.Column('rejection_reason', sa.Text(), nullable=True, comment='拒否理由'))
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('pending', 'approved', 'rejected'),
               type_=sa.String(length=20),
               comment='ステータス（pending, approved, rejected）',
               existing_comment='承認状態',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_constraint('fk_bulletin_student', type_='foreignkey')
        batch_op.drop_constraint('fk_bulletin_teacher', type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['created_by'], ['student_id'])
        batch_op.create_foreign_key(None, 'teachers', ['approved_by'], ['teacher_id'])
        batch_op.drop_column('genre')
        batch_op.drop_column('student_id')
        batch_op.drop_column('teacher_id')
        batch_op.drop_column('approval_comment')
        batch_op.drop_column('approval_date')
        batch_op.drop_column('post_id')
        batch_op.drop_column('image_paths')

    with op.batch_alter_table('bulletin_reactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bulletin_id', sa.Integer(), nullable=False, comment='掲示板ID'))
        batch_op.alter_column('reaction_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='リアクションID',
               existing_comment='リアクションID（ユニーク）',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('student_id',
               existing_type=mysql.VARCHAR(length=5),
               comment='学生ID',
               existing_comment='生徒ID（students参照）',
               existing_nullable=False)
        batch_op.alter_column('reaction_type',
               existing_type=mysql.ENUM('like', 'helpful', 'interesting', 'thanks', 'good', 'agree', 'funny', 'important', 'question', 'idea'),
               type_=sa.String(length=20),
               existing_comment='リアクションタイプ',
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index('unique_reaction')
        batch_op.drop_constraint('fk_reaction_post', type_='foreignkey')
        batch_op.drop_constraint('fk_reaction_student', type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['student_id'])
        batch_op.create_foreign_key(None, 'bulletin_board', ['bulletin_id'], ['bulletin_id'])
        batch_op.drop_column('post_id')

    with op.batch_alter_table('course_master', schema=None) as batch_op:
        batch_op.alter_column('course_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='コースID（内部参照用）',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('course_code',
               existing_type=mysql.VARCHAR(length=2),
               comment=None,
               existing_comment='コースコード（ユニーク）',
               existing_nullable=False)
        batch_op.alter_column('course_name',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='コース名',
               existing_nullable=False)
        batch_op.alter_column('course_type',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='コースタイプ（例：4year, 2year）',
               existing_nullable=True)
        batch_op.alter_column('part_time_type',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='パートタイムタイプ（例：day, night）',
               existing_nullable=True)

    with op.batch_alter_table('diaries', schema=None) as batch_op:
        batch_op.alter_column('diary_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='日記ID',
               existing_comment='日記ID（ユニーク）',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('student_id',
               existing_type=mysql.VARCHAR(length=5),
               comment='学生ID',
               existing_comment='生徒ID（students参照）',
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               comment='タイトル',
               existing_comment='日記タイトル',
               existing_nullable=False)
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               comment='内容',
               existing_comment='日記内容',
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_constraint('fk_diary_student', type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['student_id'])

    with op.batch_alter_table('diary_hashtags', schema=None) as batch_op:
        batch_op.alter_column('diary_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='日記ID',
               existing_comment='日記ID（diaries参照）',
               existing_nullable=False)
        batch_op.alter_column('hashtag_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='ハッシュタグID',
               existing_comment='ハッシュタグID（hashtags参照）',
               existing_nullable=False)
        batch_op.drop_constraint('fk_diary_hashtag_diary', type_='foreignkey')
        batch_op.drop_constraint('fk_diary_hashtag_hashtag', type_='foreignkey')
        batch_op.create_foreign_key(None, 'hashtags', ['hashtag_id'], ['hashtag_id'])
        batch_op.create_foreign_key(None, 'diaries', ['diary_id'], ['diary_id'])

    with op.batch_alter_table('diary_images', schema=None) as batch_op:
        batch_op.alter_column('image_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='画像ID',
               existing_comment='画像ID（ユニーク）',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('diary_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='日記ID',
               existing_comment='日記ID（diaries参照）',
               existing_nullable=False)
        batch_op.alter_column('image_data',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(),
               comment='画像データ',
               existing_comment='画像データ（バイナリ）',
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_constraint('fk_diary_image_diary', type_='foreignkey')
        batch_op.create_foreign_key(None, 'diaries', ['diary_id'], ['diary_id'])

    with op.batch_alter_table('empty_classrooms', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_constraint('empty_classrooms_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'classrooms', ['classroom_id'], ['classroom_id'])

    with op.batch_alter_table('hashtags', schema=None) as batch_op:
        batch_op.alter_column('hashtag_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='ハッシュタグID',
               existing_comment='ハッシュタグID（ユニーク）',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))

    with op.batch_alter_table('public_users', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='ユーザーID（ユニーク）',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='ユーザー名',
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='メールアドレス',
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='パスワード',
               existing_nullable=False)
        batch_op.alter_column('profile_image_path',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='プロフィール画像パス',
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('active', 'suspended', 'deleted'),
               comment=None,
               existing_comment='アカウント状態',
               existing_nullable=False,
               existing_server_default=sa.text("'active'"))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))

    with op.batch_alter_table('report_board', schema=None) as batch_op:
        batch_op.alter_column('report_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='報告ID',
               existing_comment='報告ID（ユニーク）',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('student_id',
               existing_type=mysql.VARCHAR(length=5),
               comment='学生ID',
               existing_comment='生徒ID（匿名の場合はNULL）',
               existing_nullable=True)
        batch_op.alter_column('image_paths',
               existing_type=mysql.VARCHAR(length=255),
               comment='画像パス',
               existing_comment='画像の相対パス（例：report_board/[report_id]/image1.jpg）',
               existing_nullable=True)
        batch_op.alter_column('video_paths',
               existing_type=mysql.VARCHAR(length=255),
               comment='動画パス',
               existing_comment='動画の相対パス（例：report_board/[report_id]/video1.mp4）',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_constraint('fk_report_student', type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['student_id'])

    with op.batch_alter_table('specialization_master', schema=None) as batch_op:
        batch_op.alter_column('specialization_id',
               existing_type=mysql.INTEGER(display_width=3, unsigned=True, zerofill=True),
               comment=None,
               existing_comment='専攻ID（ユニーク、ゼロフィル）',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('specialization_code',
               existing_type=mysql.VARCHAR(length=2),
               comment=None,
               existing_comment='専攻コード',
               existing_nullable=False)
        batch_op.alter_column('specialization_name',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='専攻名',
               existing_nullable=False)
        batch_op.alter_column('course_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='コースID（course_master参照）',
               existing_nullable=False)
        batch_op.alter_column('grade',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='学年',
               existing_nullable=False)
        batch_op.alter_column('previous_specialization_id',
               existing_type=mysql.INTEGER(display_width=3, unsigned=True, zerofill=True),
               comment=None,
               existing_comment='前の専攻ID（self-referencing）',
               existing_nullable=True)
        batch_op.drop_index('unique_specialization')
        batch_op.drop_constraint('fk_specialization_course', type_='foreignkey')
        batch_op.drop_constraint('fk_specialization_previous', type_='foreignkey')
        batch_op.create_foreign_key(None, 'specialization_master', ['previous_specialization_id'], ['specialization_id'])
        batch_op.create_foreign_key(None, 'course_master', ['course_id'], ['course_id'])

    with op.batch_alter_table('student_personal_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True, comment='内容'))
        batch_op.add_column(sa.Column('is_all_day', sa.Boolean(), nullable=True, comment='終日フラグ'))
        batch_op.add_column(sa.Column('color', sa.String(length=7), nullable=True, comment='表示色'))
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('schedule_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='スケジュールID',
               existing_comment='スケジュールID（ユニーク）',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('student_id',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.String(length=10),
               comment=None,
               existing_comment='生徒ID（students参照）',
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               comment=None,
               existing_comment='タイトル',
               existing_nullable=False)
        batch_op.alter_column('start_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='開始時間',
               existing_nullable=False)
        batch_op.alter_column('end_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='終了時間',
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               comment=None,
               existing_comment='作成日時',
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               comment=None,
               existing_comment='更新日時',
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='説明',
               existing_nullable=True)
        batch_op.drop_constraint('fk_personal_schedule_student', type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['student_id'])
        batch_op.drop_column('is_private')

    with op.batch_alter_table('student_schedules', schema=None) as batch_op:
        batch_op.alter_column('schedule_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='スケジュールID（ユニーク）',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('student_id',
               existing_type=mysql.VARCHAR(length=5),
               comment=None,
               existing_comment='生徒ID（students参照）',
               existing_nullable=False)
        batch_op.alter_column('teacher_id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=5),
               comment=None,
               existing_comment='担当教員ID（teachers参照）',
               existing_nullable=False)
        batch_op.alter_column('classroom_id',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=10),
               comment=None,
               existing_comment='教室ID（classrooms参照）',
               existing_nullable=True)
        batch_op.alter_column('subject_name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               comment=None,
               existing_comment='科目名',
               existing_nullable=False)
        batch_op.alter_column('day',
               existing_type=mysql.ENUM('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'),
               type_=sa.String(length=10),
               comment=None,
               existing_comment='曜日',
               existing_nullable=False)
        batch_op.alter_column('period',
               existing_type=mysql.ENUM('1限', '2限', '3限', '4限', '5限', '6限'),
               type_=sa.Integer(),
               comment=None,
               existing_comment='時間帯',
               existing_nullable=False)
        batch_op.alter_column('schedule_file_url',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='スケジュールファイルパス',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_constraint('fk_schedule_classroom', type_='foreignkey')
        batch_op.create_foreign_key(None, 'classrooms', ['classroom_id'], ['classroom_id'], ondelete='CASCADE')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('profile_image_path',
               existing_type=mysql.VARCHAR(length=255),
               comment='画像の相対パス',
               existing_comment='画像の相対パス（例：profiles/students/[student_id].jpg）',
               existing_nullable=True)
        batch_op.alter_column('course_id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=10),
               comment='コースID',
               existing_comment='コースID（course_master参照）',
               existing_nullable=False)
        batch_op.alter_column('specialization_id',
               existing_type=mysql.INTEGER(display_width=3, unsigned=True, zerofill=True),
               comment='専攻ID',
               existing_comment='専攻ID（specialization_master参照）',
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('active', 'leave', 'graduated', 'withdrawn'),
               nullable=False,
               existing_comment='ステータス',
               existing_server_default=sa.text("'active'"))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index('email')
        batch_op.drop_constraint('fk_student_specialization', type_='foreignkey')
        batch_op.drop_constraint('fk_student_course', type_='foreignkey')
        batch_op.create_foreign_key(None, 'specialization_master', ['specialization_id'], ['specialization_id'])
        batch_op.create_foreign_key(None, 'course_master', ['course_id'], ['course_code'])

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=False, comment='タイトル'))
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=False, comment='期限'))
        batch_op.alter_column('task_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='タスクID',
               existing_comment='タスクID（ユニーク）',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('student_id',
               existing_type=mysql.VARCHAR(length=5),
               comment='学生ID',
               existing_comment='生徒ID（students参照）',
               existing_nullable=False)
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               comment='内容',
               existing_comment='タスク内容',
               existing_nullable=False)
        batch_op.alter_column('is_completed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_comment='完了フラグ',
               existing_server_default=sa.text('0'))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_constraint('fk_task_student', type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['student_id'])

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.alter_column('teacher_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='教師ID（ユニーク）',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='教師名',
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='メールアドレス',
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='パスワード',
               existing_nullable=False)
        batch_op.alter_column('profile_image_path',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='画像の相対パス（例：profiles/teachers/[teacher_id].jpg）',
               existing_nullable=True)
        batch_op.alter_column('comment',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='コメント',
               existing_nullable=True)
        batch_op.alter_column('is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='管理者フラグ',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               comment='管理者フラグ',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('comment',
               existing_type=mysql.VARCHAR(length=255),
               comment='コメント',
               existing_nullable=True)
        batch_op.alter_column('profile_image_path',
               existing_type=mysql.VARCHAR(length=255),
               comment='画像の相対パス（例：profiles/teachers/[teacher_id].jpg）',
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               comment='パスワード',
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=255),
               comment='メールアドレス',
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               comment='教師名',
               existing_nullable=False)
        batch_op.alter_column('teacher_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='教師ID（ユニーク）',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_task_student', 'students', ['student_id'], ['student_id'], ondelete='CASCADE')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('is_completed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_comment='完了フラグ',
               existing_server_default=sa.text('0'))
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               comment='タスク内容',
               existing_comment='内容',
               existing_nullable=False)
        batch_op.alter_column('student_id',
               existing_type=mysql.VARCHAR(length=5),
               comment='生徒ID（students参照）',
               existing_comment='学生ID',
               existing_nullable=False)
        batch_op.alter_column('task_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='タスクID（ユニーク）',
               existing_comment='タスクID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('due_date')
        batch_op.drop_column('title')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_student_course', 'course_master', ['course_id'], ['course_id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_student_specialization', 'specialization_master', ['specialization_id'], ['specialization_id'], ondelete='SET NULL')
        batch_op.create_index('email', ['email'], unique=True)
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('active', 'leave', 'graduated', 'withdrawn'),
               nullable=True,
               existing_comment='ステータス',
               existing_server_default=sa.text("'active'"))
        batch_op.alter_column('specialization_id',
               existing_type=mysql.INTEGER(display_width=3, unsigned=True, zerofill=True),
               comment='専攻ID（specialization_master参照）',
               existing_comment='専攻ID',
               existing_nullable=True)
        batch_op.alter_column('course_id',
               existing_type=sa.String(length=10),
               type_=mysql.INTEGER(display_width=11),
               comment='コースID（course_master参照）',
               existing_comment='コースID',
               existing_nullable=False)
        batch_op.alter_column('profile_image_path',
               existing_type=mysql.VARCHAR(length=255),
               comment='画像の相対パス（例：profiles/students/[student_id].jpg）',
               existing_comment='画像の相対パス',
               existing_nullable=True)

    with op.batch_alter_table('student_schedules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_schedule_classroom', 'classrooms', ['classroom_id'], ['classroom_id'], ondelete='SET NULL')
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('schedule_file_url',
               existing_type=mysql.VARCHAR(length=255),
               comment='スケジュールファイルパス',
               existing_nullable=True)
        batch_op.alter_column('period',
               existing_type=sa.Integer(),
               type_=mysql.ENUM('1限', '2限', '3限', '4限', '5限', '6限'),
               comment='時間帯',
               existing_nullable=False)
        batch_op.alter_column('day',
               existing_type=sa.String(length=10),
               type_=mysql.ENUM('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'),
               comment='曜日',
               existing_nullable=False)
        batch_op.alter_column('subject_name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               comment='科目名',
               existing_nullable=False)
        batch_op.alter_column('classroom_id',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=50),
               comment='教室ID（classrooms参照）',
               existing_nullable=True)
        batch_op.alter_column('teacher_id',
               existing_type=sa.String(length=5),
               type_=mysql.INTEGER(display_width=11),
               comment='担当教員ID（teachers参照）',
               existing_nullable=False)
        batch_op.alter_column('student_id',
               existing_type=mysql.VARCHAR(length=5),
               comment='生徒ID（students参照）',
               existing_nullable=False)
        batch_op.alter_column('schedule_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='スケジュールID（ユニーク）',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('student_personal_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_private', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=True, comment='プライベートフラグ（1: 非公開、0: 公開）'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_personal_schedule_student', 'students', ['student_id'], ['student_id'], ondelete='CASCADE')
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               comment='説明',
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               comment='更新日時',
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               comment='作成日時',
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('end_time',
               existing_type=mysql.DATETIME(),
               comment='終了時間',
               existing_nullable=False)
        batch_op.alter_column('start_time',
               existing_type=mysql.DATETIME(),
               comment='開始時間',
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               comment='タイトル',
               existing_nullable=False)
        batch_op.alter_column('student_id',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=5),
               comment='生徒ID（students参照）',
               existing_nullable=False)
        batch_op.alter_column('schedule_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='スケジュールID（ユニーク）',
               existing_comment='スケジュールID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('id')
        batch_op.drop_column('color')
        batch_op.drop_column('is_all_day')
        batch_op.drop_column('content')

    with op.batch_alter_table('specialization_master', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_specialization_previous', 'specialization_master', ['previous_specialization_id'], ['specialization_id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_specialization_course', 'course_master', ['course_id'], ['course_id'], ondelete='CASCADE')
        batch_op.create_index('unique_specialization', ['course_id', 'specialization_code', 'grade'], unique=True)
        batch_op.alter_column('previous_specialization_id',
               existing_type=mysql.INTEGER(display_width=3, unsigned=True, zerofill=True),
               comment='前の専攻ID（self-referencing）',
               existing_nullable=True)
        batch_op.alter_column('grade',
               existing_type=mysql.INTEGER(display_width=11),
               comment='学年',
               existing_nullable=False)
        batch_op.alter_column('course_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='コースID（course_master参照）',
               existing_nullable=False)
        batch_op.alter_column('specialization_name',
               existing_type=mysql.VARCHAR(length=100),
               comment='専攻名',
               existing_nullable=False)
        batch_op.alter_column('specialization_code',
               existing_type=mysql.VARCHAR(length=2),
               comment='専攻コード',
               existing_nullable=False)
        batch_op.alter_column('specialization_id',
               existing_type=mysql.INTEGER(display_width=3, unsigned=True, zerofill=True),
               comment='専攻ID（ユニーク、ゼロフィル）',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('report_board', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_report_student', 'students', ['student_id'], ['student_id'], ondelete='SET NULL')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('video_paths',
               existing_type=mysql.VARCHAR(length=255),
               comment='動画の相対パス（例：report_board/[report_id]/video1.mp4）',
               existing_comment='動画パス',
               existing_nullable=True)
        batch_op.alter_column('image_paths',
               existing_type=mysql.VARCHAR(length=255),
               comment='画像の相対パス（例：report_board/[report_id]/image1.jpg）',
               existing_comment='画像パス',
               existing_nullable=True)
        batch_op.alter_column('student_id',
               existing_type=mysql.VARCHAR(length=5),
               comment='生徒ID（匿名の場合はNULL）',
               existing_comment='学生ID',
               existing_nullable=True)
        batch_op.alter_column('report_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='報告ID（ユニーク）',
               existing_comment='報告ID',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('public_users', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('active', 'suspended', 'deleted'),
               comment='アカウント状態',
               existing_nullable=False,
               existing_server_default=sa.text("'active'"))
        batch_op.alter_column('profile_image_path',
               existing_type=mysql.VARCHAR(length=255),
               comment='プロフィール画像パス',
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               comment='パスワード',
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=255),
               comment='メールアドレス',
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=50),
               comment='ユーザー名',
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='ユーザーID（ユニーク）',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('hashtags', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('hashtag_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='ハッシュタグID（ユニーク）',
               existing_comment='ハッシュタグID',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('empty_classrooms', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('empty_classrooms_ibfk_1', 'classrooms', ['classroom_id'], ['classroom_id'], ondelete='CASCADE')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('diary_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_diary_image_diary', 'diaries', ['diary_id'], ['diary_id'], ondelete='CASCADE')
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('image_data',
               existing_type=sa.LargeBinary(),
               type_=mysql.LONGBLOB(),
               comment='画像データ（バイナリ）',
               existing_comment='画像データ',
               existing_nullable=False)
        batch_op.alter_column('diary_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='日記ID（diaries参照）',
               existing_comment='日記ID',
               existing_nullable=False)
        batch_op.alter_column('image_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='画像ID（ユニーク）',
               existing_comment='画像ID',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('diary_hashtags', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_diary_hashtag_hashtag', 'hashtags', ['hashtag_id'], ['hashtag_id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_diary_hashtag_diary', 'diaries', ['diary_id'], ['diary_id'], ondelete='CASCADE')
        batch_op.alter_column('hashtag_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='ハッシュタグID（hashtags参照）',
               existing_comment='ハッシュタグID',
               existing_nullable=False)
        batch_op.alter_column('diary_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='日記ID（diaries参照）',
               existing_comment='日記ID',
               existing_nullable=False)

    with op.batch_alter_table('diaries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_diary_student', 'students', ['student_id'], ['student_id'], ondelete='CASCADE')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               comment='日記内容',
               existing_comment='内容',
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               comment='日記タイトル',
               existing_comment='タイトル',
               existing_nullable=False)
        batch_op.alter_column('student_id',
               existing_type=mysql.VARCHAR(length=5),
               comment='生徒ID（students参照）',
               existing_comment='学生ID',
               existing_nullable=False)
        batch_op.alter_column('diary_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='日記ID（ユニーク）',
               existing_comment='日記ID',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('course_master', schema=None) as batch_op:
        batch_op.alter_column('part_time_type',
               existing_type=mysql.VARCHAR(length=10),
               comment='パートタイムタイプ（例：day, night）',
               existing_nullable=True)
        batch_op.alter_column('course_type',
               existing_type=mysql.VARCHAR(length=10),
               comment='コースタイプ（例：4year, 2year）',
               existing_nullable=True)
        batch_op.alter_column('course_name',
               existing_type=mysql.VARCHAR(length=100),
               comment='コース名',
               existing_nullable=False)
        batch_op.alter_column('course_code',
               existing_type=mysql.VARCHAR(length=2),
               comment='コースコード（ユニーク）',
               existing_nullable=False)
        batch_op.alter_column('course_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='コースID（内部参照用）',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('bulletin_reactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='投稿ID（bulletin_board参照）'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_reaction_student', 'students', ['student_id'], ['student_id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_reaction_post', 'bulletin_board', ['post_id'], ['post_id'], ondelete='CASCADE')
        batch_op.create_index('unique_reaction', ['post_id', 'student_id', 'reaction_type'], unique=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('reaction_type',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('like', 'helpful', 'interesting', 'thanks', 'good', 'agree', 'funny', 'important', 'question', 'idea'),
               existing_comment='リアクションタイプ',
               existing_nullable=False)
        batch_op.alter_column('student_id',
               existing_type=mysql.VARCHAR(length=5),
               comment='生徒ID（students参照）',
               existing_comment='学生ID',
               existing_nullable=False)
        batch_op.alter_column('reaction_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='リアクションID（ユニーク）',
               existing_comment='リアクションID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('bulletin_id')

    with op.batch_alter_table('bulletin_board', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_paths', mysql.VARCHAR(length=255), nullable=True, comment='画像の相対パス（例：bulletin_board/[post_id]/image1.jpg）'))
        batch_op.add_column(sa.Column('post_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='投稿ID（ユニーク）'))
        batch_op.add_column(sa.Column('approval_date', mysql.TIMESTAMP(), nullable=True, comment='承認日時'))
        batch_op.add_column(sa.Column('approval_comment', mysql.TEXT(), nullable=True, comment='教師からのコメント'))
        batch_op.add_column(sa.Column('teacher_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='承認した教師ID（teachers参照）'))
        batch_op.add_column(sa.Column('student_id', mysql.VARCHAR(length=5), nullable=False, comment='生徒ID（students参照）'))
        batch_op.add_column(sa.Column('genre', mysql.VARCHAR(length=50), nullable=False, comment='ジャンル'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_bulletin_teacher', 'teachers', ['teacher_id'], ['teacher_id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_bulletin_student', 'students', ['student_id'], ['student_id'], ondelete='CASCADE')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('pending', 'approved', 'rejected'),
               comment='承認状態',
               existing_comment='ステータス（pending, approved, rejected）',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('created_by')
        batch_op.drop_column('title')
        batch_op.drop_column('bulletin_id')

    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_constraint('fk_announcement_teacher', type_='foreignkey')
        batch_op.create_foreign_key('fk_announcement_teacher', 'teachers', ['created_by'], ['teacher_id'], ondelete='CASCADE')
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(display_width=11),
               comment='作成者の教師ID（teachers参照）',
               existing_nullable=False)
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               comment='内容',
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=255),
               comment='タイトル',
               existing_nullable=False)
        batch_op.alter_column('announcement_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='お知らせID（ユニーク）',
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('is_active')
        batch_op.drop_column('is_important')

    op.create_table('private_chat',
    sa.Column('chat_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='チャットID（ユニーク）'),
    sa.Column('sender_id', mysql.VARCHAR(length=5), nullable=False, comment='送信者の生徒ID（students参照）'),
    sa.Column('receiver_id', mysql.VARCHAR(length=5), nullable=False, comment='受信者の生徒ID（students参照）'),
    sa.Column('message', mysql.TEXT(), nullable=False, comment='メッセージ内容'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False, comment='作成日時'),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False, comment='更新日時'),
    sa.ForeignKeyConstraint(['receiver_id'], ['students.student_id'], name='fk_chat_receiver', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['students.student_id'], name='fk_chat_sender', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('comments',
    sa.Column('comment_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='コメントID（ユニーク）'),
    sa.Column('schedule_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='スケジュールID（student_schedules参照）'),
    sa.Column('comment', mysql.TEXT(), nullable=False, comment='コメント内容'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False, comment='作成日時'),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False, comment='更新日時'),
    sa.ForeignKeyConstraint(['schedule_id'], ['student_schedules.schedule_id'], name='fk_comment_schedule', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('schedule_comments')
    op.drop_table('student_profiles')
    op.drop_table('student_contacts')
    op.drop_table('student_base_schedules')
    op.drop_table('student_auth')
    op.drop_table('reports')
    op.drop_table('system_config')
    op.drop_table('admins')
    # ### end Alembic commands ###
