"""empty message

Revision ID: 92476a17191d
Revises: 0d4da5f4dc2c
Create Date: 2025-02-21 18:30:27.736693

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92476a17191d'
down_revision = '0d4da5f4dc2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_base_schedules')
    with op.batch_alter_table('bulletin_board', schema=None) as batch_op:
        batch_op.drop_column('post_id')
        batch_op.drop_column('image_paths')

    with op.batch_alter_table('bulletin_reactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bulletin_id', sa.Integer(), nullable=False, comment='掲示板ID'))
        batch_op.alter_column('reaction_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='リアクションID',
               existing_comment='リアクションID（ユニーク）',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('student_id',
               existing_type=mysql.VARCHAR(length=5),
               comment='学生ID',
               existing_comment='生徒ID（students参照）',
               existing_nullable=False)
        batch_op.alter_column('reaction_type',
               existing_type=mysql.ENUM('like', 'helpful', 'interesting', 'thanks', 'good', 'agree', 'funny', 'important', 'question', 'idea'),
               type_=sa.String(length=20),
               existing_comment='リアクションタイプ',
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index('unique_reaction')
        batch_op.drop_constraint('fk_reaction_post', type_='foreignkey')
        batch_op.drop_constraint('fk_reaction_student', type_='foreignkey')
        batch_op.create_foreign_key(None, 'bulletin_board', ['bulletin_id'], ['bulletin_id'])
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['student_id'])
        batch_op.drop_column('post_id')

    with op.batch_alter_table('course_master', schema=None) as batch_op:
        batch_op.alter_column('course_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='コースID（内部参照用）',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('course_code',
               existing_type=mysql.VARCHAR(length=2),
               comment=None,
               existing_comment='コースコード（ユニーク）',
               existing_nullable=False)
        batch_op.alter_column('course_name',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='コース名',
               existing_nullable=False)
        batch_op.alter_column('course_type',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='コースタイプ（例：4year, 2year）',
               existing_nullable=True)
        batch_op.alter_column('part_time_type',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='パートタイムタイプ（例：day, night）',
               existing_nullable=True)

    with op.batch_alter_table('diaries', schema=None) as batch_op:
        batch_op.alter_column('diary_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='日記ID',
               existing_comment='日記ID（ユニーク）',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('student_id',
               existing_type=mysql.VARCHAR(length=5),
               comment='学生ID',
               existing_comment='生徒ID（students参照）',
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               comment='タイトル',
               existing_comment='日記タイトル',
               existing_nullable=False)
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               comment='内容',
               existing_comment='日記内容',
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_constraint('fk_diary_student', type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['student_id'])

    with op.batch_alter_table('diary_hashtags', schema=None) as batch_op:
        batch_op.alter_column('diary_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='日記ID',
               existing_comment='日記ID（diaries参照）',
               existing_nullable=False)
        batch_op.alter_column('hashtag_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='ハッシュタグID',
               existing_comment='ハッシュタグID（hashtags参照）',
               existing_nullable=False)
        batch_op.drop_constraint('fk_diary_hashtag_diary', type_='foreignkey')
        batch_op.drop_constraint('fk_diary_hashtag_hashtag', type_='foreignkey')
        batch_op.create_foreign_key(None, 'hashtags', ['hashtag_id'], ['hashtag_id'])
        batch_op.create_foreign_key(None, 'diaries', ['diary_id'], ['diary_id'])

    with op.batch_alter_table('diary_images', schema=None) as batch_op:
        batch_op.alter_column('image_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='画像ID',
               existing_comment='画像ID（ユニーク）',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('diary_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='日記ID',
               existing_comment='日記ID（diaries参照）',
               existing_nullable=False)
        batch_op.alter_column('image_data',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(),
               comment='画像データ',
               existing_comment='画像データ（バイナリ）',
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_constraint('fk_diary_image_diary', type_='foreignkey')
        batch_op.create_foreign_key(None, 'diaries', ['diary_id'], ['diary_id'])

    with op.batch_alter_table('empty_classrooms', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_constraint('empty_classrooms_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'classrooms', ['classroom_id'], ['classroom_id'])

    with op.batch_alter_table('hashtags', schema=None) as batch_op:
        batch_op.alter_column('hashtag_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='ハッシュタグID',
               existing_comment='ハッシュタグID（ユニーク）',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))

    with op.batch_alter_table('public_users', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='ユーザーID（ユニーク）',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='ユーザー名',
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='メールアドレス',
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='パスワード',
               existing_nullable=False)
        batch_op.alter_column('profile_image_path',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='プロフィール画像パス',
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('active', 'suspended', 'deleted'),
               comment=None,
               existing_comment='アカウント状態',
               existing_nullable=False,
               existing_server_default=sa.text("'active'"))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))

    with op.batch_alter_table('report_board', schema=None) as batch_op:
        batch_op.alter_column('report_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='報告ID',
               existing_comment='報告ID（ユニーク）',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('student_id',
               existing_type=mysql.VARCHAR(length=5),
               comment='学生ID',
               existing_comment='生徒ID（匿名の場合はNULL）',
               existing_nullable=True)
        batch_op.alter_column('image_paths',
               existing_type=mysql.VARCHAR(length=255),
               comment='画像パス',
               existing_comment='画像の相対パス（例：report_board/[report_id]/image1.jpg）',
               existing_nullable=True)
        batch_op.alter_column('video_paths',
               existing_type=mysql.VARCHAR(length=255),
               comment='動画パス',
               existing_comment='動画の相対パス（例：report_board/[report_id]/video1.mp4）',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_constraint('fk_report_student', type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['student_id'])

    with op.batch_alter_table('schedule_comments', schema=None) as batch_op:
        batch_op.drop_constraint('schedule_comments_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'student_schedules', ['schedule_id'], ['schedule_id'])

    with op.batch_alter_table('specialization_master', schema=None) as batch_op:
        batch_op.alter_column('specialization_id',
               existing_type=mysql.INTEGER(display_width=3, unsigned=True, zerofill=True),
               comment=None,
               existing_comment='専攻ID（ユニーク、ゼロフィル）',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('specialization_code',
               existing_type=mysql.VARCHAR(length=2),
               comment=None,
               existing_comment='専攻コード',
               existing_nullable=False)
        batch_op.alter_column('specialization_name',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='専攻名',
               existing_nullable=False)
        batch_op.alter_column('course_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='コースID（course_master参照）',
               existing_nullable=False)
        batch_op.alter_column('grade',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='学年',
               existing_nullable=False)
        batch_op.alter_column('previous_specialization_id',
               existing_type=mysql.INTEGER(display_width=3, unsigned=True, zerofill=True),
               comment=None,
               existing_comment='前の専攻ID（self-referencing）',
               existing_nullable=True)
        batch_op.drop_index('unique_specialization')
        batch_op.drop_constraint('fk_specialization_previous', type_='foreignkey')
        batch_op.drop_constraint('fk_specialization_course', type_='foreignkey')
        batch_op.create_foreign_key(None, 'course_master', ['course_id'], ['course_id'])
        batch_op.create_foreign_key(None, 'specialization_master', ['previous_specialization_id'], ['specialization_id'])

    with op.batch_alter_table('student_personal_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True, comment='内容'))
        batch_op.add_column(sa.Column('is_all_day', sa.Boolean(), nullable=True, comment='終日フラグ'))
        batch_op.add_column(sa.Column('color', sa.String(length=7), nullable=True, comment='表示色'))
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('schedule_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='スケジュールID',
               existing_comment='スケジュールID（ユニーク）',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('student_id',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.String(length=10),
               comment=None,
               existing_comment='生徒ID（students参照）',
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               comment=None,
               existing_comment='タイトル',
               existing_nullable=False)
        batch_op.alter_column('start_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='開始時間',
               existing_nullable=False)
        batch_op.alter_column('end_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='終了時間',
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               comment=None,
               existing_comment='作成日時',
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               comment=None,
               existing_comment='更新日時',
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='説明',
               existing_nullable=True)
        batch_op.drop_constraint('fk_personal_schedule_student', type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['student_id'])
        batch_op.drop_column('is_private')

    with op.batch_alter_table('student_schedules', schema=None) as batch_op:
        batch_op.alter_column('schedule_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='スケジュールID（ユニーク）',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('student_id',
               existing_type=mysql.VARCHAR(length=5),
               comment=None,
               existing_comment='生徒ID（students参照）',
               existing_nullable=False)
        batch_op.alter_column('teacher_id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=5),
               comment=None,
               existing_comment='担当教員ID（teachers参照）',
               existing_nullable=False)
        batch_op.alter_column('classroom_id',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=10),
               comment=None,
               existing_comment='教室ID（classrooms参照）',
               existing_nullable=True)
        batch_op.alter_column('subject_name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               comment=None,
               existing_comment='科目名',
               existing_nullable=False)
        batch_op.alter_column('day',
               existing_type=mysql.ENUM('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'),
               type_=sa.String(length=10),
               comment=None,
               existing_comment='曜日',
               existing_nullable=False)
        batch_op.alter_column('period',
               existing_type=mysql.ENUM('1限', '2限', '3限', '4限', '5限', '6限'),
               type_=sa.Integer(),
               comment=None,
               existing_comment='時間帯',
               existing_nullable=False)
        batch_op.alter_column('schedule_file_url',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='スケジュールファイルパス',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_constraint('fk_schedule_classroom', type_='foreignkey')
        batch_op.create_foreign_key(None, 'classrooms', ['classroom_id'], ['classroom_id'], ondelete='CASCADE')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('profile_image_path',
               existing_type=mysql.VARCHAR(length=255),
               comment='画像の相対パス',
               existing_comment='画像の相対パス（例：profiles/students/[student_id].jpg）',
               existing_nullable=True)
        batch_op.alter_column('course_id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=10),
               comment='コースID',
               existing_comment='コースID（course_master参照）',
               existing_nullable=False)
        batch_op.alter_column('specialization_id',
               existing_type=mysql.INTEGER(display_width=3, unsigned=True, zerofill=True),
               comment='専攻ID',
               existing_comment='専攻ID（specialization_master参照）',
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('active', 'leave', 'graduated', 'withdrawn'),
               nullable=False,
               existing_comment='ステータス',
               existing_server_default=sa.text("'active'"))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index('email')
        batch_op.drop_constraint('fk_student_specialization', type_='foreignkey')
        batch_op.drop_constraint('fk_student_course', type_='foreignkey')
        batch_op.create_foreign_key(None, 'course_master', ['course_id'], ['course_code'])
        batch_op.create_foreign_key(None, 'specialization_master', ['specialization_id'], ['specialization_id'])

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=False, comment='タイトル'))
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=False, comment='期限'))
        batch_op.alter_column('task_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='タスクID',
               existing_comment='タスクID（ユニーク）',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('student_id',
               existing_type=mysql.VARCHAR(length=5),
               comment='学生ID',
               existing_comment='生徒ID（students参照）',
               existing_nullable=False)
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               comment='内容',
               existing_comment='タスク内容',
               existing_nullable=False)
        batch_op.alter_column('is_completed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_comment='完了フラグ',
               existing_server_default=sa.text('0'))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_constraint('fk_task_student', type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['student_id'])

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.alter_column('teacher_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='教師ID（ユニーク）',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='教師名',
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='メールアドレス',
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='パスワード',
               existing_nullable=False)
        batch_op.alter_column('profile_image_path',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='画像の相対パス（例：profiles/teachers/[teacher_id].jpg）',
               existing_nullable=True)
        batch_op.alter_column('comment',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='コメント',
               existing_nullable=True)
        batch_op.alter_column('is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='管理者フラグ',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               comment='管理者フラグ',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('comment',
               existing_type=mysql.VARCHAR(length=255),
               comment='コメント',
               existing_nullable=True)
        batch_op.alter_column('profile_image_path',
               existing_type=mysql.VARCHAR(length=255),
               comment='画像の相対パス（例：profiles/teachers/[teacher_id].jpg）',
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               comment='パスワード',
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=255),
               comment='メールアドレス',
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               comment='教師名',
               existing_nullable=False)
        batch_op.alter_column('teacher_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='教師ID（ユニーク）',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_task_student', 'students', ['student_id'], ['student_id'], ondelete='CASCADE')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('is_completed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_comment='完了フラグ',
               existing_server_default=sa.text('0'))
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               comment='タスク内容',
               existing_comment='内容',
               existing_nullable=False)
        batch_op.alter_column('student_id',
               existing_type=mysql.VARCHAR(length=5),
               comment='生徒ID（students参照）',
               existing_comment='学生ID',
               existing_nullable=False)
        batch_op.alter_column('task_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='タスクID（ユニーク）',
               existing_comment='タスクID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('due_date')
        batch_op.drop_column('title')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_student_course', 'course_master', ['course_id'], ['course_id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_student_specialization', 'specialization_master', ['specialization_id'], ['specialization_id'], ondelete='SET NULL')
        batch_op.create_index('email', ['email'], unique=True)
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('active', 'leave', 'graduated', 'withdrawn'),
               nullable=True,
               existing_comment='ステータス',
               existing_server_default=sa.text("'active'"))
        batch_op.alter_column('specialization_id',
               existing_type=mysql.INTEGER(display_width=3, unsigned=True, zerofill=True),
               comment='専攻ID（specialization_master参照）',
               existing_comment='専攻ID',
               existing_nullable=True)
        batch_op.alter_column('course_id',
               existing_type=sa.String(length=10),
               type_=mysql.INTEGER(display_width=11),
               comment='コースID（course_master参照）',
               existing_comment='コースID',
               existing_nullable=False)
        batch_op.alter_column('profile_image_path',
               existing_type=mysql.VARCHAR(length=255),
               comment='画像の相対パス（例：profiles/students/[student_id].jpg）',
               existing_comment='画像の相対パス',
               existing_nullable=True)

    with op.batch_alter_table('student_schedules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_schedule_classroom', 'classrooms', ['classroom_id'], ['classroom_id'], ondelete='SET NULL')
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('schedule_file_url',
               existing_type=mysql.VARCHAR(length=255),
               comment='スケジュールファイルパス',
               existing_nullable=True)
        batch_op.alter_column('period',
               existing_type=sa.Integer(),
               type_=mysql.ENUM('1限', '2限', '3限', '4限', '5限', '6限'),
               comment='時間帯',
               existing_nullable=False)
        batch_op.alter_column('day',
               existing_type=sa.String(length=10),
               type_=mysql.ENUM('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'),
               comment='曜日',
               existing_nullable=False)
        batch_op.alter_column('subject_name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               comment='科目名',
               existing_nullable=False)
        batch_op.alter_column('classroom_id',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=50),
               comment='教室ID（classrooms参照）',
               existing_nullable=True)
        batch_op.alter_column('teacher_id',
               existing_type=sa.String(length=5),
               type_=mysql.INTEGER(display_width=11),
               comment='担当教員ID（teachers参照）',
               existing_nullable=False)
        batch_op.alter_column('student_id',
               existing_type=mysql.VARCHAR(length=5),
               comment='生徒ID（students参照）',
               existing_nullable=False)
        batch_op.alter_column('schedule_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='スケジュールID（ユニーク）',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('student_personal_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_private', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=True, comment='プライベートフラグ（1: 非公開、0: 公開）'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_personal_schedule_student', 'students', ['student_id'], ['student_id'], ondelete='CASCADE')
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               comment='説明',
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               comment='更新日時',
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               comment='作成日時',
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('end_time',
               existing_type=mysql.DATETIME(),
               comment='終了時間',
               existing_nullable=False)
        batch_op.alter_column('start_time',
               existing_type=mysql.DATETIME(),
               comment='開始時間',
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               comment='タイトル',
               existing_nullable=False)
        batch_op.alter_column('student_id',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=5),
               comment='生徒ID（students参照）',
               existing_nullable=False)
        batch_op.alter_column('schedule_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='スケジュールID（ユニーク）',
               existing_comment='スケジュールID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('id')
        batch_op.drop_column('color')
        batch_op.drop_column('is_all_day')
        batch_op.drop_column('content')

    with op.batch_alter_table('specialization_master', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_specialization_course', 'course_master', ['course_id'], ['course_id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_specialization_previous', 'specialization_master', ['previous_specialization_id'], ['specialization_id'], ondelete='SET NULL')
        batch_op.create_index('unique_specialization', ['course_id', 'specialization_code', 'grade'], unique=True)
        batch_op.alter_column('previous_specialization_id',
               existing_type=mysql.INTEGER(display_width=3, unsigned=True, zerofill=True),
               comment='前の専攻ID（self-referencing）',
               existing_nullable=True)
        batch_op.alter_column('grade',
               existing_type=mysql.INTEGER(display_width=11),
               comment='学年',
               existing_nullable=False)
        batch_op.alter_column('course_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='コースID（course_master参照）',
               existing_nullable=False)
        batch_op.alter_column('specialization_name',
               existing_type=mysql.VARCHAR(length=100),
               comment='専攻名',
               existing_nullable=False)
        batch_op.alter_column('specialization_code',
               existing_type=mysql.VARCHAR(length=2),
               comment='専攻コード',
               existing_nullable=False)
        batch_op.alter_column('specialization_id',
               existing_type=mysql.INTEGER(display_width=3, unsigned=True, zerofill=True),
               comment='専攻ID（ユニーク、ゼロフィル）',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('schedule_comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('schedule_comments_ibfk_1', 'student_base_schedules', ['schedule_id'], ['id'])

    with op.batch_alter_table('report_board', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_report_student', 'students', ['student_id'], ['student_id'], ondelete='SET NULL')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('video_paths',
               existing_type=mysql.VARCHAR(length=255),
               comment='動画の相対パス（例：report_board/[report_id]/video1.mp4）',
               existing_comment='動画パス',
               existing_nullable=True)
        batch_op.alter_column('image_paths',
               existing_type=mysql.VARCHAR(length=255),
               comment='画像の相対パス（例：report_board/[report_id]/image1.jpg）',
               existing_comment='画像パス',
               existing_nullable=True)
        batch_op.alter_column('student_id',
               existing_type=mysql.VARCHAR(length=5),
               comment='生徒ID（匿名の場合はNULL）',
               existing_comment='学生ID',
               existing_nullable=True)
        batch_op.alter_column('report_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='報告ID（ユニーク）',
               existing_comment='報告ID',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('public_users', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('active', 'suspended', 'deleted'),
               comment='アカウント状態',
               existing_nullable=False,
               existing_server_default=sa.text("'active'"))
        batch_op.alter_column('profile_image_path',
               existing_type=mysql.VARCHAR(length=255),
               comment='プロフィール画像パス',
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               comment='パスワード',
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=255),
               comment='メールアドレス',
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=50),
               comment='ユーザー名',
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='ユーザーID（ユニーク）',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('hashtags', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('hashtag_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='ハッシュタグID（ユニーク）',
               existing_comment='ハッシュタグID',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('empty_classrooms', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('empty_classrooms_ibfk_1', 'classrooms', ['classroom_id'], ['classroom_id'], ondelete='CASCADE')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('diary_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_diary_image_diary', 'diaries', ['diary_id'], ['diary_id'], ondelete='CASCADE')
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('image_data',
               existing_type=sa.LargeBinary(),
               type_=mysql.LONGBLOB(),
               comment='画像データ（バイナリ）',
               existing_comment='画像データ',
               existing_nullable=False)
        batch_op.alter_column('diary_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='日記ID（diaries参照）',
               existing_comment='日記ID',
               existing_nullable=False)
        batch_op.alter_column('image_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='画像ID（ユニーク）',
               existing_comment='画像ID',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('diary_hashtags', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_diary_hashtag_hashtag', 'hashtags', ['hashtag_id'], ['hashtag_id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_diary_hashtag_diary', 'diaries', ['diary_id'], ['diary_id'], ondelete='CASCADE')
        batch_op.alter_column('hashtag_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='ハッシュタグID（hashtags参照）',
               existing_comment='ハッシュタグID',
               existing_nullable=False)
        batch_op.alter_column('diary_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='日記ID（diaries参照）',
               existing_comment='日記ID',
               existing_nullable=False)

    with op.batch_alter_table('diaries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_diary_student', 'students', ['student_id'], ['student_id'], ondelete='CASCADE')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               comment='日記内容',
               existing_comment='内容',
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               comment='日記タイトル',
               existing_comment='タイトル',
               existing_nullable=False)
        batch_op.alter_column('student_id',
               existing_type=mysql.VARCHAR(length=5),
               comment='生徒ID（students参照）',
               existing_comment='学生ID',
               existing_nullable=False)
        batch_op.alter_column('diary_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='日記ID（ユニーク）',
               existing_comment='日記ID',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('course_master', schema=None) as batch_op:
        batch_op.alter_column('part_time_type',
               existing_type=mysql.VARCHAR(length=10),
               comment='パートタイムタイプ（例：day, night）',
               existing_nullable=True)
        batch_op.alter_column('course_type',
               existing_type=mysql.VARCHAR(length=10),
               comment='コースタイプ（例：4year, 2year）',
               existing_nullable=True)
        batch_op.alter_column('course_name',
               existing_type=mysql.VARCHAR(length=100),
               comment='コース名',
               existing_nullable=False)
        batch_op.alter_column('course_code',
               existing_type=mysql.VARCHAR(length=2),
               comment='コースコード（ユニーク）',
               existing_nullable=False)
        batch_op.alter_column('course_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='コースID（内部参照用）',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('bulletin_reactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='投稿ID（bulletin_board参照）'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_reaction_student', 'students', ['student_id'], ['student_id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_reaction_post', 'bulletin_board', ['post_id'], ['post_id'], ondelete='CASCADE')
        batch_op.create_index('unique_reaction', ['post_id', 'student_id', 'reaction_type'], unique=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_comment='更新日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_comment='作成日時',
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('reaction_type',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('like', 'helpful', 'interesting', 'thanks', 'good', 'agree', 'funny', 'important', 'question', 'idea'),
               existing_comment='リアクションタイプ',
               existing_nullable=False)
        batch_op.alter_column('student_id',
               existing_type=mysql.VARCHAR(length=5),
               comment='生徒ID（students参照）',
               existing_comment='学生ID',
               existing_nullable=False)
        batch_op.alter_column('reaction_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='リアクションID（ユニーク）',
               existing_comment='リアクションID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('bulletin_id')

    with op.batch_alter_table('bulletin_board', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_paths', mysql.VARCHAR(length=255), nullable=True, comment='画像の相対パス（例：bulletin_board/[post_id]/image1.jpg）'))
        batch_op.add_column(sa.Column('post_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='投稿ID（ユニーク）'))

    op.create_table('student_base_schedules',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('student_id', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('start_time', mysql.DATETIME(), nullable=False),
    sa.Column('end_time', mysql.DATETIME(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], name='student_base_schedules_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
